'use client';

import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Divider from '@mui/material/Divider';
import Stack from '@mui/material/Stack';
import Link from 'next/link';

function ExpandIcon() {
  return <Typography sx={{ fontSize: '1.2rem' }}>+</Typography>;
}

interface FAQItem {
  question: string;
  answer: React.ReactNode;
}

const FAQS: FAQItem[] = [
  {
    question: 'How do recommendations work?',
    answer: (
      <>
        Our recommendation engine uses a 4-layer system: rule-based scoring (matching your
        preferences on player count, time, complexity, genres, and moods), content-based filtering
        (finding games similar to ones you like using vector embeddings), collaborative filtering
        (learning from what other users with similar tastes enjoy), and semantic analysis (understanding
        free-text descriptions of what you&apos;re looking for). The results are blended together and
        re-ranked for diversity so you get a mix of perfect matches and pleasant surprises.
      </>
    ),
  },
  {
    question: 'Where does your game data come from?',
    answer: (
      <>
        We aggregate data from multiple trusted sources: BoardGameGeek (board games), RAWG and IGDB
        (video games), plus a hand-curated collection of word and party games. This gives us a
        catalog of 100,000+ games with ratings, descriptions, categories, mechanics, and more.
      </>
    ),
  },
  {
    question: 'Is Recommend a Game free to use?',
    answer: (
      <>
        Yes! All core features are completely free: getting recommendations, browsing games, saving
        favorites, writing reviews, and using the dice roller. We support the site through
        non-intrusive advertising.
      </>
    ),
  },
  {
    question: 'Do I need an account?',
    answer: (
      <>
        You can get recommendations and browse games without an account. Creating a free account
        unlocks additional features: saving favorites, writing reviews, creating custom dice skins,
        saving preference presets, and getting better recommendations over time as we learn from your
        feedback.
      </>
    ),
  },
  {
    question: 'How does the "Not This" / "More Like This" feature work?',
    answer: (
      <>
        When you see a recommendation, you can click &quot;Not This&quot; to tell us it&apos;s not
        what you&apos;re looking for, or &quot;More Like This&quot; to signal you want similar games.
        This feedback trains your personal preference profile so future recommendations get more
        accurate. The more feedback you give, the better your recommendations become.
      </>
    ),
  },
  {
    question: 'What is the dice roller?',
    answer: (
      <>
        It&apos;s a physics-based 3D d20 dice roller you can use for tabletop gaming or just for
        fun. You can customize your dice with different colors, materials, and textures using our
        Dice Creator, and share your designs in the Dice Gallery for others to use and vote on.
      </>
    ),
  },
  {
    question: 'Is my data safe?',
    answer: (
      <>
        Yes. We use Supabase for authentication and data storage with row-level security policies,
        encrypted connections (HTTPS everywhere), and we never share your personal data with third
        parties for marketing purposes. See our{' '}
        <Link href="/privacy" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Privacy Policy
        </Link>{' '}
        for full details.
      </>
    ),
  },
  {
    question: 'Can I delete my account and data?',
    answer: (
      <>
        Yes. You can request account deletion and data removal by contacting us at{' '}
        <a href="mailto:contact@recommendagame.com" style={{ color: 'inherit', textDecoration: 'underline' }}>
          contact@recommendagame.com
        </a>
        . We will process your request within 30 days as outlined in our{' '}
        <Link href="/privacy" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Privacy Policy
        </Link>
        .
      </>
    ),
  },
  {
    question: 'Why are some recommendations not perfect?',
    answer: (
      <>
        Recommendations are generated by an automated system and are based on the preferences you
        provide, community data, and algorithmic scoring. No system is perfect — but you can improve
        your results by filling out the questionnaire in detail, using the &quot;Not This&quot; and
        &quot;More Like This&quot; buttons, and trying different preference presets. The more context
        you give us, the better the results.
      </>
    ),
  },
  {
    question: 'How do I report a bug or suggest a feature?',
    answer: (
      <>
        Head over to our{' '}
        <Link href="/contact" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Contact page
        </Link>{' '}
        and send us an email. We read every message and appreciate all feedback.
      </>
    ),
  },
];

export default function FAQView() {
  return (
    <Container maxWidth="md" sx={{ py: 8 }}>
      <Typography variant="h3" fontWeight={800} sx={{ mb: 1 }}>
        Frequently Asked Questions
      </Typography>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 4 }}>
        Everything you need to know about Recommend a Game.
      </Typography>

      <Divider sx={{ mb: 4 }} />

      <Stack spacing={1}>
        {FAQS.map((faq, i) => (
          <Accordion key={i} disableGutters elevation={0} sx={{ '&:before': { display: 'none' }, border: '1px solid', borderColor: 'divider', borderRadius: '8px !important', mb: 1 }}>
            <AccordionSummary expandIcon={<ExpandIcon />}>
              <Typography fontWeight={600}>{faq.question}</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="body1" color="text.secondary" sx={{ lineHeight: 1.8 }}>
                {faq.answer}
              </Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Stack>

      <Divider sx={{ my: 4 }} />

      <Typography variant="body2" color="text.secondary">
        Still have questions?{' '}
        <Link href="/contact" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Contact us
        </Link>
        {' '}and we&apos;ll get back to you within 48 hours.
      </Typography>
    </Container>
  );
}
