'use client';

import Container from '@mui/material/Container';
import Typography from '@mui/material/Typography';
import Accordion from '@mui/material/Accordion';
import AccordionSummary from '@mui/material/AccordionSummary';
import AccordionDetails from '@mui/material/AccordionDetails';
import Divider from '@mui/material/Divider';
import Stack from '@mui/material/Stack';
import Link from 'next/link';
import JsonLd from '@/components/JsonLd';

function ExpandIcon() {
  return <Typography sx={{ fontSize: '1.2rem' }}>+</Typography>;
}

interface FAQItem {
  question: string;
  answer: React.ReactNode;
}

const FAQS: FAQItem[] = [
  {
    question: 'How do recommendations work?',
    answer: (
      <>
        Our recommendation engine uses a 6-layer system: natural language understanding (an AI
        parses what you type in plain English), relevance-first candidate search (7 strategies
        run in parallel across 80,000+ games), multi-dimensional scoring (10 weighted dimensions
        like genre match, player count, and complexity), semantic similarity (vector embeddings
        capture meaning that tags miss), AI re-ranking (a second AI reviews the top candidates
        with common sense), and learning from you (your feedback sharpens your profile over time).
        A smart caching layer means similar searches from other users are near-instant.
      </>
    ),
  },
  {
    question: 'Where does your game data come from?',
    answer: (
      <>
        We aggregate data from multiple trusted sources: BoardGameGeek (board games), RAWG and IGDB
        (video games), plus a hand-curated collection of word and party games. This gives us a
        catalog of 100,000+ games with ratings, descriptions, categories, mechanics, and more.
      </>
    ),
  },
  {
    question: 'Is boredgame.lol free to use?',
    answer: (
      <>
        Yes! All core features are completely free: getting recommendations, browsing games, saving
        favorites, writing reviews, and using the dice roller. We support the site through
        non-intrusive advertising.
      </>
    ),
  },
  {
    question: 'Do I need an account?',
    answer: (
      <>
        You can get recommendations and browse games without an account. Creating a free account
        unlocks additional features: saving favorites, writing reviews, creating custom dice skins,
        saving preference presets, and getting better recommendations over time as we learn from your
        feedback.
      </>
    ),
  },
  {
    question: 'How does the "Not This" / "More Like This" feature work?',
    answer: (
      <>
        When you see a recommendation, you can click &quot;Not This&quot; to tell us it&apos;s not
        what you&apos;re looking for, or &quot;More Like This&quot; to signal you want similar games.
        This feedback trains your personal preference profile so future recommendations get more
        accurate. The more feedback you give, the better your recommendations become.
      </>
    ),
  },
  {
    question: 'What is the dice roller?',
    answer: (
      <>
        It&apos;s a physics-based 3D d20 dice roller you can use for tabletop gaming or just for
        fun. You can customize your dice with different colors, materials, and textures using our
        Dice Creator, and share your designs in the Dice Gallery for others to use and vote on.
      </>
    ),
  },
  {
    question: 'Is my data safe?',
    answer: (
      <>
        Yes. We use Supabase for authentication and data storage with row-level security policies,
        encrypted connections (HTTPS everywhere), and we never share your personal data with third
        parties for marketing purposes. See our{' '}
        <Link href="/privacy" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Privacy Policy
        </Link>{' '}
        for full details.
      </>
    ),
  },
  {
    question: 'Can I delete my account and data?',
    answer: (
      <>
        Yes. You can request account deletion and data removal by contacting us at{' '}
        <a href="mailto:contact@boredgame.lol" style={{ color: 'inherit', textDecoration: 'underline' }}>
          contact@boredgame.lol
        </a>
        . We will process your request within 30 days as outlined in our{' '}
        <Link href="/privacy" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Privacy Policy
        </Link>
        .
      </>
    ),
  },
  {
    question: 'Why are some recommendations not perfect?',
    answer: (
      <>
        Recommendations are generated by an automated system and are based on the preferences you
        provide, community data, and algorithmic scoring. No system is perfect, but you can improve
        your results by filling out the questionnaire in detail, using the &quot;Not This&quot; and
        &quot;More Like This&quot; buttons, and trying different preference presets. The more context
        you give us, the better the results.
      </>
    ),
  },
  {
    question: 'How do I report a bug or suggest a feature?',
    answer: (
      <>
        Head over to our{' '}
        <Link href="/contact" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Contact page
        </Link>{' '}
        and send us an email. We read every message and appreciate all feedback.
      </>
    ),
  },
];

// Plain text answers for JSON-LD (Google can't parse JSX)
const FAQ_JSONLD_ANSWERS: string[] = [
  'Our recommendation engine uses a 6-layer system: natural language understanding, relevance-first candidate search (7 parallel strategies), multi-dimensional scoring (10 dimensions), semantic similarity via vector embeddings, AI re-ranking, and learning from your feedback. A smart semantic caching layer makes similar searches near-instant.',
  'We aggregate data from BoardGameGeek (board games), RAWG and IGDB (video games), plus a hand-curated collection of word and party games. This gives us a catalog of 100,000+ games.',
  'Yes! All core features are completely free. We support the site through non-intrusive advertising.',
  'You can get recommendations and browse games without an account. Creating a free account unlocks saving favorites, writing reviews, creating custom dice skins, and getting better recommendations over time.',
  'When you click "Not This" or "More Like This", this feedback trains your personal preference profile so future recommendations get more accurate.',
  'It\'s a physics-based 3D d20 dice roller. You can customize dice with different colors and materials using the Dice Creator, and share designs in the Dice Gallery.',
  'Yes. We use Supabase for authentication and data storage with row-level security policies and encrypted connections. We never share personal data with third parties for marketing.',
  'Yes. You can request account deletion and data removal by contacting us or through the Settings page.',
  'Recommendations are generated by an automated system. You can improve results by filling out the questionnaire in detail and using the feedback buttons.',
  'Head over to our Contact page and send us an email. We read every message and appreciate all feedback.',
];

export default function FAQView() {
  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: FAQS.map((faq, i) => ({
      '@type': 'Question',
      name: faq.question,
      acceptedAnswer: {
        '@type': 'Answer',
        text: FAQ_JSONLD_ANSWERS[i] ?? '',
      },
    })),
  };

  return (
    <Container maxWidth="md" sx={{ py: 8 }}>
      <JsonLd data={faqJsonLd} />
      <Typography variant="h3" fontWeight={800} sx={{ mb: 1 }}>
        Frequently Asked Questions
      </Typography>
      <Typography variant="body1" color="text.secondary" sx={{ mb: 4 }}>
        Everything you need to know about boredgame.lol.
      </Typography>

      <Divider sx={{ mb: 4 }} />

      <Stack spacing={1}>
        {FAQS.map((faq, i) => (
          <Accordion key={i} disableGutters elevation={0} sx={{ '&:before': { display: 'none' }, border: '1px solid', borderColor: 'divider', borderRadius: '8px !important', mb: 1 }}>
            <AccordionSummary expandIcon={<ExpandIcon />}>
              <Typography fontWeight={600}>{faq.question}</Typography>
            </AccordionSummary>
            <AccordionDetails>
              <Typography variant="body1" color="text.secondary" sx={{ lineHeight: 1.8 }}>
                {faq.answer}
              </Typography>
            </AccordionDetails>
          </Accordion>
        ))}
      </Stack>

      <Divider sx={{ my: 4 }} />

      <Typography variant="body2" color="text.secondary">
        Still have questions?{' '}
        <Link href="/contact" style={{ color: 'inherit', textDecoration: 'underline' }}>
          Contact us
        </Link>
        {' '}and we&apos;ll get back to you within 48 hours.
      </Typography>
    </Container>
  );
}
