/**
 * Topic selection logic for the daily blog generation pipeline.
 *
 * Extracts the 365-day topic rotation and day-of-year picker from the
 * blog generate route so it can be reused and tested independently.
 */

import type { TopicTemplate } from './types';

// 365 article topic templates, one for every day of the year
export const TOPIC_TEMPLATES: TopicTemplate[] = [
  // -- Player count focused (1-20) --
  { template: 'Best Solo Board Games to Play Alone', category: null },
  { template: 'Best {category} Games for 2 Players', category: 'Strategy' },
  { template: 'Top 3-Player Games That Actually Work Well', category: null },
  { template: 'Best Board Games for 4 Players', category: null },
  { template: 'Best Party Games for 5+ Players', category: 'Party' },
  { template: 'Games That Work Great at Every Player Count', category: null },
  { template: 'Best Games for Large Groups of 6-8 Players', category: null },
  { template: 'Two-Player Games That Are Better Than You Think', category: null },
  { template: 'Games That Scale Perfectly from 2 to 6 Players', category: null },
  { template: 'Best Games for Exactly 3 Players', category: null },
  { template: 'Solo Board Games That Feel Like Multiplayer', category: null },
  { template: 'Best 2-Player Competitive Games', category: 'Strategy' },
  { template: 'Cooperative Games That Work at 2 Players', category: 'Cooperative' },
  { template: 'Best Games for Big Game Night Groups', category: null },
  { template: 'Games for 7+ Players That Aren\'t Just Party Games', category: null },
  { template: 'Best Head-to-Head Dueling Games', category: null },
  { template: 'Solo Games You Can Play in Under an Hour', category: null },
  { template: 'Best 4-Player Strategy Games', category: 'Strategy' },
  { template: 'Two-Player Games for Couples', category: null },
  { template: 'Best Games When You Only Have 2 People', category: null },

  // -- Time focused (21-40) --
  { template: 'Top 10 Quick Games Under 30 Minutes', category: null },
  { template: 'Games You Can Finish in Under 15 Minutes', category: null },
  { template: 'Best Games for a 1-Hour Game Session', category: null },
  { template: 'Epic Games Worth the 3+ Hour Investment', category: null },
  { template: 'Best Filler Games Between Longer Sessions', category: null },
  { template: 'Quick Card Games for Lunch Breaks', category: 'Card Game' },
  { template: 'Games That Play in Exactly 20 Minutes', category: null },
  { template: 'Best Long Strategy Games for a Full Afternoon', category: 'Strategy' },
  { template: 'Speed Games That Get Your Heart Racing', category: null },
  { template: 'Best 45-Minute Board Games', category: null },
  { template: 'Games You Can Teach in Under 5 Minutes', category: null },
  { template: 'Board Games for When You Have All Day', category: null },
  { template: 'Quick 2-Player Games for Weeknights', category: null },
  { template: 'Best Real-Time Board Games', category: null },
  { template: 'Games That End Before They Overstay Their Welcome', category: null },
  { template: 'Short Games with Deep Strategy', category: null },
  { template: 'Best 90-Minute Strategy Games', category: 'Strategy' },
  { template: 'Games for a Quick 10-Minute Break', category: null },
  { template: 'Marathon Games That Are Worth Every Minute', category: null },
  { template: 'Fastest Board Games to Set Up and Play', category: null },

  // -- Complexity focused (41-60) --
  { template: 'Best {category} Games for Beginners', category: 'Gateway' },
  { template: 'Complex Strategy Games Worth the Learning Curve', category: 'Heavy Strategy' },
  { template: 'Best Games to Play with Non-Gamers', category: 'Light' },
  { template: 'Gateway Games That Convert Non-Gamers', category: 'Gateway' },
  { template: 'Heavy Euro Games for Serious Strategists', category: 'Euro' },
  { template: 'Light Games with Surprising Depth', category: null },
  { template: 'Best Medium-Weight Strategy Games', category: 'Strategy' },
  { template: 'Board Games Anyone Can Learn in 2 Minutes', category: null },
  { template: 'Games That Look Complex But Are Actually Simple', category: null },
  { template: 'Best Heavy Games for Experienced Players', category: null },
  { template: 'Simple Rules, Deep Gameplay: The Best of Both Worlds', category: null },
  { template: 'Games to Graduate To After Catan', category: null },
  { template: 'Best Entry-Level Strategy Games', category: 'Strategy' },
  { template: 'Games Your Parents Would Actually Enjoy', category: null },
  { template: 'Brain-Burning Games for Puzzle Lovers', category: null },
  { template: 'Best Games for People Who Think They Don\'t Like Board Games', category: null },
  { template: 'Lightweight Games That Are Never Boring', category: null },
  { template: 'Most Beginner-Friendly Strategy Games', category: null },
  { template: 'Games for Hardcore Gamers Only', category: null },
  { template: 'The Perfect First Game for New Board Gamers', category: null },

  // -- Mechanic focused (61-100) --
  { template: 'Worker Placement Games Ranked', category: 'Worker Placement' },
  { template: 'Best Deck-Building Games for Every Budget', category: 'Deck Building' },
  { template: 'Best Area Control Games for Competitive Players', category: 'Area Control' },
  { template: 'Top Deduction Games That Test Your Brain', category: 'Deduction' },
  { template: 'Best Engine Building Games of All Time', category: 'Engine Building' },
  { template: 'Best Abstract Strategy Games', category: 'Abstract' },
  { template: 'Top Tile-Laying Games', category: 'Tile Placement' },
  { template: 'Best Draft Games Where Picks Matter', category: 'Drafting' },
  { template: 'Hidden Role Games That Create Epic Moments', category: 'Hidden Identity' },
  { template: 'Best Auction and Bidding Games', category: 'Auction' },
  { template: 'Roll-and-Write Games Worth Playing', category: 'Roll and Write' },
  { template: 'Best Push-Your-Luck Games', category: 'Push Your Luck' },
  { template: 'Route Building Games Beyond Ticket to Ride', category: 'Route Building' },
  { template: 'Best Hand Management Games', category: 'Hand Management' },
  { template: 'Pattern Building Games That Look Beautiful', category: 'Pattern Building' },
  { template: 'Best Pick-Up-and-Deliver Games', category: 'Pick Up and Deliver' },
  { template: 'Negotiation Games That Ruin Friendships (in a Good Way)', category: 'Negotiation' },
  { template: 'Best Resource Management Games', category: 'Resource Management' },
  { template: 'Trick-Taking Card Games Ranked', category: 'Trick Taking' },
  { template: 'Best Set Collection Games', category: 'Set Collection' },
  { template: 'Asymmetric Games Where Everyone Plays Differently', category: 'Asymmetric' },
  { template: 'Best Campaign and Legacy Games', category: 'Legacy' },
  { template: 'Bluffing Games That Reward a Good Poker Face', category: 'Bluffing' },
  { template: 'Best Tableau Building Games', category: 'Tableau Building' },
  { template: 'Dice Games That Aren\'t Just About Luck', category: 'Dice Rolling' },
  { template: 'Best Dexterity Games for Physical Fun', category: 'Dexterity' },
  { template: 'Network Building Games for Strategic Minds', category: 'Network Building' },
  { template: 'Best Action Point Games', category: 'Action Points' },
  { template: 'Simultaneous Action Games for No Downtime', category: 'Simultaneous Action' },
  { template: 'Best Variable Player Power Games', category: 'Variable Player Powers' },
  { template: 'Memory Games That Are Actually Fun for Adults', category: 'Memory' },
  { template: 'Best Trading Games', category: 'Trading' },
  { template: 'Modular Board Games That Are Different Every Time', category: 'Modular Board' },
  { template: 'Programming Games Where You Plan Your Moves', category: 'Programmed Movement' },
  { template: 'Best Games with Bag Building Mechanics', category: 'Bag Building' },
  { template: 'Rondel Games Explained and Ranked', category: 'Rondel' },
  { template: 'Best Combat-Focused Board Games', category: 'Combat' },
  { template: 'Exploration Games for Adventurous Players', category: 'Exploration' },
  { template: 'Tech Tree Games for Builder Types', category: 'Tech Tree' },
  { template: 'Best Grid Movement Games', category: 'Grid Movement' },

  // -- Theme focused (101-140) --
  { template: 'Best Fantasy Board Games', category: 'Fantasy' },
  { template: 'Top Sci-Fi Board Games', category: 'Science Fiction' },
  { template: 'Best Horror Board Games for Halloween', category: 'Horror' },
  { template: 'Historical Board Games That Teach You Something', category: 'Historical' },
  { template: 'Best Pirate-Themed Games', category: 'Pirates' },
  { template: 'Space Exploration Board Games', category: 'Space' },
  { template: 'Best Medieval Board Games', category: 'Medieval' },
  { template: 'Zombie Board Games Ranked', category: 'Zombies' },
  { template: 'Best Nature and Wildlife Board Games', category: 'Nature' },
  { template: 'Civilization Building Games for Empire Lovers', category: 'Civilization' },
  { template: 'Best Mystery and Crime Board Games', category: 'Mystery' },
  { template: 'Mythology Board Games from Around the World', category: 'Mythology' },
  { template: 'Best Farming and Agriculture Games', category: 'Farming' },
  { template: 'War Games for Armchair Generals', category: 'Wargame' },
  { template: 'Best Animal-Themed Board Games', category: 'Animals' },
  { template: 'Superhero Board Games That Actually Work', category: 'Superheroes' },
  { template: 'Best Train and Railroad Board Games', category: 'Trains' },
  { template: 'Post-Apocalyptic Board Games', category: 'Post-Apocalyptic' },
  { template: 'Best City Building Board Games', category: 'City Building' },
  { template: 'Ocean and Maritime Board Games', category: 'Nautical' },
  { template: 'Best Political and Intrigue Board Games', category: 'Political' },
  { template: 'Racing Board Games That Feel Fast', category: 'Racing' },
  { template: 'Best Dinosaur Board Games', category: 'Dinosaurs' },
  { template: 'Egyptian-Themed Board Games', category: 'Ancient Egypt' },
  { template: 'Best Steampunk Board Games', category: 'Steampunk' },
  { template: 'Viking and Norse Board Games', category: 'Vikings' },
  { template: 'Best Games Set in Asia', category: 'Asia' },
  { template: 'Board Games About Food and Cooking', category: 'Food' },
  { template: 'Best Games with a Space Theme', category: 'Space' },
  { template: 'Games Set in the Wild West', category: 'Western' },
  { template: 'Best Board Games About Trading and Economics', category: 'Economic' },
  { template: 'Lovecraft and Cthulhu Board Games', category: 'Lovecraftian' },
  { template: 'Best Board Games Set in Japan', category: 'Japan' },
  { template: 'Games About Building Kingdoms and Empires', category: 'Kingdom Building' },
  { template: 'Best Detective and Investigation Games', category: 'Detective' },
  { template: 'Board Games with a World War 2 Setting', category: 'World War 2' },
  { template: 'Best Dragon-Themed Board Games', category: 'Dragons' },
  { template: 'Board Games About Exploration and Discovery', category: 'Exploration' },
  { template: 'Espionage and Spy Board Games', category: 'Spies' },
  { template: 'Best Board Games About Magic and Sorcery', category: 'Magic' },

  // -- Occasion focused (141-180) --
  { template: 'Best {category} Games for Date Night', category: 'Romance' },
  { template: 'Best Games for a Rainy Day Indoors', category: null },
  { template: 'Games for Holiday Gatherings', category: null },
  { template: 'Best Board Games for Road Trips', category: null },
  { template: 'Games for Camping Without Electricity', category: null },
  { template: 'Best Games for a Cozy Winter Night', category: null },
  { template: 'Games to Play at the Beach or Park', category: null },
  { template: 'Best Board Games for Thanksgiving', category: null },
  { template: 'Games for New Year\'s Eve Parties', category: null },
  { template: 'Best Board Games for Christmas Gifts', category: null },
  { template: 'Games to Play While Waiting at the Airport', category: null },
  { template: 'Best Games for Summer Vacation', category: null },
  { template: 'Games for a Lazy Sunday Afternoon', category: null },
  { template: 'Best Board Games for Bachelor and Bachelorette Parties', category: null },
  { template: 'Games for Team Building at Work', category: null },
  { template: 'Best Games for a Sleepover', category: null },
  { template: 'Games That Make Dinner Parties More Fun', category: null },
  { template: 'Best Board Games for a First Date', category: null },
  { template: 'Games for Long Car Rides', category: null },
  { template: 'Best Games for Tailgating', category: null },
  { template: 'Board Games for Sick Days at Home', category: null },
  { template: 'Best Games for a Cabin Weekend', category: null },
  { template: 'Games to Play at a Coffee Shop', category: null },
  { template: 'Best Board Games for Retirement', category: null },
  { template: 'Games for Killing Time During Travel Delays', category: null },
  { template: 'Best Board Games for Halloween Night', category: null },
  { template: 'Games for a Friendsgiving', category: null },
  { template: 'Best Games for Spring Break', category: null },
  { template: 'Board Games for After Dinner', category: null },
  { template: 'Games for a Power Outage', category: null },
  { template: 'Best Games for a Pool Party', category: null },
  { template: 'Board Games for Camping Trips', category: null },
  { template: 'Games for a Game Night Marathon', category: null },
  { template: 'Best Board Games for Brunch', category: null },
  { template: 'Games for a Housewarming Party', category: null },
  { template: 'Best Games for Valentine\'s Day', category: null },
  { template: 'Games for a Birthday Party', category: null },
  { template: 'Best Board Games for Mother\'s Day', category: null },
  { template: 'Games for Father\'s Day', category: null },
  { template: 'Best Board Games for a Game Cafe', category: null },

  // -- Audience focused (181-220) --
  { template: 'Best {category} Board Games for Families', category: 'Family' },
  { template: 'Board Games for Teenagers', category: null },
  { template: 'Best Board Games for College Students', category: null },
  { template: 'Games for Kids Ages 5-8', category: 'Children' },
  { template: 'Best Board Games for Seniors', category: null },
  { template: 'Games for Couples Who Love Competition', category: null },
  { template: 'Best Board Games for Introverts', category: null },
  { template: 'Games for People Who Love Puzzles', category: 'Puzzle' },
  { template: 'Best Board Games for Math Lovers', category: null },
  { template: 'Games for History Buffs', category: 'Historical' },
  { template: 'Best Board Games for Book Lovers', category: null },
  { template: 'Games for Creative People', category: null },
  { template: 'Best Board Games for Competitive Players', category: null },
  { template: 'Games for People Who Hate Conflict', category: 'Cooperative' },
  { template: 'Best Board Games for Planners and Organizers', category: null },
  { template: 'Games for People Who Love Storytelling', category: 'Narrative' },
  { template: 'Best Board Games for Engineers', category: null },
  { template: 'Games for Teachers and Educators', category: 'Educational' },
  { template: 'Best Board Games for Artists', category: null },
  { template: 'Games for D&D Fans', category: 'RPG' },
  { template: 'Best Board Games for Video Gamers', category: null },
  { template: 'Games for People New to the Hobby', category: null },
  { template: 'Best Board Games for Kids Under 5', category: null },
  { template: 'Games for Mixed Age Groups', category: null },
  { template: 'Best Board Games for Tweens', category: null },
  { template: 'Games for Strategy Game Veterans', category: null },
  { template: 'Best Games for Roommates', category: null },
  { template: 'Board Games for Long-Distance Relationships', category: null },
  { template: 'Best Games for Newlyweds', category: null },
  { template: 'Games for Multi-Generational Families', category: null },
  { template: 'Best Board Games for Nerds', category: null },
  { template: 'Games for People Who Love Trivia', category: 'Trivia' },
  { template: 'Best Board Games for Sports Fans', category: 'Sports' },
  { template: 'Games for Anime and Manga Fans', category: null },
  { template: 'Best Board Games for Music Lovers', category: null },
  { template: 'Games for Science Fiction Fans', category: 'Science Fiction' },
  { template: 'Best Board Games for Horror Fans', category: 'Horror' },
  { template: 'Games for Wine and Board Game Night', category: null },
  { template: 'Best Board Games for Beer Lovers', category: null },
  { template: 'Games That Make Great Birthday Gifts', category: null },

  // -- Comparison and vs posts (221-260) --
  { template: 'Euro Games vs Ameritrash: What to Play', category: null },
  { template: 'Board Games That Replaced Video Games for Us', category: null },
  { template: 'Cooperative vs Competitive: Which Style Is for You', category: null },
  { template: 'Kickstarter Games vs Retail Games: Worth the Hype?', category: null },
  { template: 'Digital Board Games vs Physical: Pros and Cons', category: null },
  { template: 'Catan vs Ticket to Ride: The Classic Showdown', category: null },
  { template: 'Wingspan vs Everdell: Which Nature Game Wins?', category: null },
  { template: 'Card Games vs Board Games: What\'s the Difference?', category: null },
  { template: 'Legacy Games vs One-Shot Games', category: null },
  { template: 'Thematic vs Abstract Games: A Breakdown', category: null },
  { template: 'Solo Gaming vs Multiplayer: Both Are Valid', category: null },
  { template: 'Cheap Board Games vs Premium: Where to Spend', category: null },
  { template: 'Old Classics vs Modern Board Games', category: null },
  { template: 'Light Games vs Heavy Games: Finding Your Weight', category: null },
  { template: 'Board Games vs Escape Rooms', category: null },
  { template: 'Deck Builders vs Bag Builders: What Sets Them Apart', category: null },
  { template: 'Miniatures Games vs Card Games', category: null },
  { template: 'Strategy Games vs Party Games: When to Play Each', category: null },
  { template: 'Indie Board Games vs Big Publisher Games', category: null },
  { template: 'Print and Play Games vs Retail Board Games', category: null },
  { template: 'Board Game Cafes vs Hosting Game Night at Home', category: null },
  { template: 'Asymmetric Games vs Symmetric Games', category: null },
  { template: 'Real-Time Games vs Turn-Based Games', category: null },
  { template: 'Worker Placement vs Engine Building: What\'s Better?', category: null },
  { template: 'Dungeon Crawlers vs RPG Board Games', category: null },
  { template: 'Narrative Games vs Sandbox Games', category: null },
  { template: 'Board Games vs Tabletop RPGs', category: null },
  { template: 'Co-op Dungeon Crawlers vs Competitive Ones', category: null },
  { template: 'Gateway Games vs Midweight Games: The Next Step', category: null },
  { template: 'Hidden Traitor Games vs Hidden Role Games', category: null },
  { template: 'Board Games vs Puzzles for Solo Entertainment', category: null },
  { template: 'Roll-and-Write vs Flip-and-Write Games', category: null },
  { template: 'Area Control vs Area Majority: Know the Difference', category: null },
  { template: 'Board Games with Apps vs Pure Analog Games', category: null },
  { template: 'Mass Market vs Hobby Board Games', category: null },
  { template: 'Tile Placement vs Tile Laying: A Comparison', category: null },
  { template: 'Economic Games vs Resource Management Games', category: null },
  { template: 'Team Games vs Free-for-All Games', category: null },
  { template: 'Short Campaign Games vs Full Legacy Games', category: null },
  { template: 'Board Games vs Card Games for Travel', category: null },

  // -- Guide and how-to posts (261-300) --
  { template: 'How to Start a Board Game Collection', category: null },
  { template: 'How to Teach Board Games Without Putting People to Sleep', category: null },
  { template: 'How to Host the Perfect Game Night', category: null },
  { template: 'How to Choose a Board Game for Someone Else', category: null },
  { template: 'How to Store and Organize Your Board Games', category: null },
  { template: 'How to Find Hidden Gem Board Games', category: null },
  { template: 'How to Play Board Games Online with Friends', category: null },
  { template: 'How to Get Into Board Games as an Adult', category: null },
  { template: 'Board Game Etiquette: Unwritten Rules Everyone Should Know', category: null },
  { template: 'How to Budget for Board Games Without Going Broke', category: null },
  { template: 'How to Convince Your Friends to Try Board Games', category: null },
  { template: 'How to Choose Between Two Board Games', category: null },
  { template: 'How to Find a Board Game Group Near You', category: null },
  { template: 'How to Read Board Game Reviews Critically', category: null },
  { template: 'Board Game Accessories That Are Actually Worth Buying', category: null },
  { template: 'How to Protect and Sleeve Your Board Game Cards', category: null },
  { template: 'How to Paint Board Game Miniatures for Beginners', category: null },
  { template: 'Best Board Game Tables and Surfaces', category: null },
  { template: 'How to Deal with Sore Losers at Game Night', category: null },
  { template: 'How to Downsize Your Board Game Collection', category: null },
  { template: 'Board Game Subscription Boxes: Are They Worth It?', category: null },
  { template: 'How to Play Board Games with Kids Without Dumbing It Down', category: null },
  { template: 'How to Find Board Games at Thrift Stores', category: null },
  { template: 'Best Board Game Podcasts and YouTube Channels', category: null },
  { template: 'How to Start a Board Game Club', category: null },
  { template: 'Best Websites for Board Game Deals', category: null },
  { template: 'How to Keep Track of Games You Want to Play', category: null },
  { template: 'Tips for Playing Board Games Competitively', category: null },
  { template: 'How to Introduce Heavy Games to Casual Players', category: null },
  { template: 'Best Board Game Apps for Learning Rules', category: null },
  { template: 'How to Run a Board Game Tournament', category: null },
  { template: 'How to Fix Damaged Board Game Components', category: null },
  { template: 'Best 3D Printed Board Game Accessories', category: null },
  { template: 'How to Build Custom Inserts for Board Games', category: null },
  { template: 'Board Game Shelving Ideas for Small Spaces', category: null },
  { template: 'How to Track Your Board Game Plays', category: null },
  { template: 'Best Apps for Scoring Board Games', category: null },
  { template: 'How to Find Replacement Parts for Board Games', category: null },
  { template: 'Board Game Travel Cases and Portable Solutions', category: null },
  { template: 'How to Rate Board Games: What Makes a 10/10?', category: null },

  // -- Lists and rankings (301-340) --
  { template: 'Top {category} Games for Game Night', category: 'Strategy' },
  { template: 'Underrated Board Games with Amazing Mechanics', category: null },
  { template: 'Best Tabletop Adaptations of Popular Franchises', category: null },
  { template: 'Top Card Games That Fit in Your Pocket', category: 'Card Game' },
  { template: 'Games That Are Better Than Their Ratings Suggest', category: null },
  { template: 'Top Games with Amazing Artwork', category: null },
  { template: 'Best Dungeon Crawl and RPG Board Games', category: 'RPG' },
  { template: 'Hidden Gem {category} Games You Missed', category: 'Adventure' },
  { template: 'Best {category} Games Released Recently', category: 'Thematic' },
  { template: 'Cooperative Games Everyone Should Try', category: 'Cooperative' },
  { template: 'Most Beautiful Board Games on Your Shelf', category: null },
  { template: 'Best Board Games Under $20', category: null },
  { template: 'Best Board Games Under $50', category: null },
  { template: 'Board Games Worth the Splurge Over $100', category: null },
  { template: 'Most Replayable Board Games of All Time', category: null },
  { template: 'Board Games with the Best Components', category: null },
  { template: 'Games with the Most Satisfying Combos', category: null },
  { template: 'Board Games with the Best Themes', category: null },
  { template: 'Most Innovative Board Games Released This Year', category: null },
  { template: 'Best Board Games You\'ve Never Heard Of', category: null },
  { template: 'Games That Deserve More Attention', category: null },
  { template: 'Board Games That Went Viral on Social Media', category: null },
  { template: 'Best Board Games of the Last Decade', category: null },
  { template: 'Classic Board Games That Still Hold Up', category: null },
  { template: 'Board Games That Are Better with Expansions', category: null },
  { template: 'Best Board Game Expansions Ever Made', category: null },
  { template: 'Most Overrated Board Games', category: null },
  { template: 'Board Games That Are Impossible to Find', category: null },
  { template: 'Best Free Print-and-Play Board Games', category: null },
  { template: 'Board Games with the Funniest Moments', category: null },
  { template: 'Games with the Most Stressful Decisions', category: null },
  { template: 'Board Games That Make You Think Differently', category: null },
  { template: 'Best Board Games for Learning New Skills', category: null },
  { template: 'Games with the Cleverest Mechanics', category: null },
  { template: 'Board Games with the Best Rulebooks', category: null },
  { template: 'Shortest Board Games with the Most Depth', category: null },
  { template: 'Board Games with the Most Dramatic Endings', category: null },
  { template: 'Games That Get Better Every Time You Play', category: null },
  { template: 'Best Board Games Based on Video Games', category: null },
  { template: 'Board Games Based on Movies and TV Shows', category: null },

  // -- Video game crossover (341-365) --
  { template: 'Best Video Games for Board Game Lovers', category: null, allowVideoGames: true },
  { template: 'Board Games That Feel Like Video Games', category: null, allowVideoGames: true },
  { template: 'Best Digital Versions of Board Games', category: null, allowVideoGames: true },
  { template: 'Video Games with Board Game Mechanics', category: null, allowVideoGames: true },
  { template: 'Best Roguelike Board Games', category: null, allowVideoGames: true },
  { template: 'Board Games for Minecraft Fans', category: null, allowVideoGames: true },
  { template: 'Strategy Video Games That Started as Board Games', category: null, allowVideoGames: true },
  { template: 'Best Board Games on Tabletop Simulator', category: null, allowVideoGames: true },
  { template: 'Mobile Board Game Apps Worth Downloading', category: null, allowVideoGames: true },
  { template: 'Board Games for Stardew Valley Fans', category: null, allowVideoGames: true },
  { template: 'Best Board Games for Zelda Fans', category: null, allowVideoGames: true },
  { template: 'Games for Fans of Civilization and 4X Games', category: '4X', allowVideoGames: true },
  { template: 'Best Party Video Games vs Party Board Games', category: null, allowVideoGames: true },
  { template: 'Board Games for Dark Souls Fans', category: null, allowVideoGames: true },
  { template: 'Games for Fans of XCOM and Tactical Combat', category: null, allowVideoGames: true },
  { template: 'Board Games That Inspired Video Games', category: null, allowVideoGames: true },
  { template: 'Best Board Games on Board Game Arena', category: null, allowVideoGames: true },
  { template: 'Games for Fans of Pokemon and Monster Collecting', category: null, allowVideoGames: true },
  { template: 'Board Games for Animal Crossing Fans', category: null, allowVideoGames: true },
  { template: 'Best Board Games for Final Fantasy Fans', category: null, allowVideoGames: true },
  { template: 'Games for Fans of Puzzle Video Games', category: null, allowVideoGames: true },
  { template: 'Board Games for Survival Horror Fans', category: null, allowVideoGames: true },
  { template: 'Best Board Games for MMO Fans', category: null, allowVideoGames: true },
  { template: 'Card Games for Magic: The Gathering Fans', category: null, allowVideoGames: true },
  { template: 'Board Games for Fans of Grand Strategy Games', category: null, allowVideoGames: true },

  // ═══════════════════════════════════════════════════════════════════
  // NEW FORMAT TOPICS (366-730)
  // ═══════════════════════════════════════════════════════════════════

  // -- Opinion / Hot Take (25) --
  { template: 'Why Catan Is the Most Overrated Board Game', category: null, format: 'opinion' },
  { template: 'The Problem With Deck Building in Modern Board Games', category: null, format: 'opinion' },
  { template: 'Board Games Are Better Than Video Games and Here Is Why', category: null, format: 'opinion' },
  { template: 'Why Monopoly Deserves More Respect', category: null, format: 'opinion' },
  { template: 'Stop Buying Board Games You Will Never Play', category: null, format: 'opinion' },
  { template: 'The Case Against House Rules in Board Games', category: null, format: 'opinion' },
  { template: 'Why Worker Placement Games All Feel the Same', category: 'Worker Placement', format: 'opinion' },
  { template: 'Kickstarter Board Games Are Overpriced and Overhyped', category: null, format: 'opinion' },
  { template: 'Cooperative Games Are Better Than Competitive Ones', category: 'Cooperative', format: 'opinion' },
  { template: 'Why Theme Matters More Than Mechanics', category: null, format: 'opinion' },
  { template: 'The Problem With Legacy Games Nobody Talks About', category: null, format: 'opinion' },
  { template: 'Why Party Games Get No Respect From Serious Gamers', category: 'Party', format: 'opinion' },
  { template: 'Board Game Complexity Is Not the Same as Depth', category: null, format: 'opinion' },
  { template: 'Why You Should Play More Abstract Games', category: 'Abstract', format: 'opinion' },
  { template: 'The Golden Age of Board Games Is Right Now', category: null, format: 'opinion' },
  { template: 'Why Card Drafting Is the Best Board Game Mechanic', category: null, format: 'opinion' },
  { template: 'Roll and Write Games Are Underrated', category: null, format: 'opinion' },
  { template: 'Why Everyone Should Own at Least One Heavy Euro Game', category: 'Economic', format: 'opinion' },
  { template: 'Board Game Reviews Are Broken and Here Is How to Fix Them', category: null, format: 'opinion' },
  { template: 'Why Two Player Games Are the Best Way to Game', category: null, format: 'opinion' },
  { template: 'Stop Sleeving Your Cards, It Is Not Worth It', category: null, format: 'opinion' },
  { template: 'The Myth of the Perfect Gateway Game', category: null, format: 'opinion' },
  { template: 'Why Area Control Games Create the Best Rivalries', category: 'Strategy', format: 'opinion' },
  { template: 'Solo Board Gaming Is Not Sad, It Is Strategic', category: null, format: 'opinion' },
  { template: 'Why Every Board Game Collection Needs a Dexterity Game', category: null, format: 'opinion' },

  // -- Deep Dives (25) --
  { template: 'Everything You Need to Know About Gloomhaven', category: null, format: 'deep-dive' },
  { template: 'The Complete History of Worker Placement Games', category: 'Worker Placement', format: 'deep-dive' },
  { template: 'Why Wingspan Changed Board Gaming Forever', category: null, format: 'deep-dive' },
  { template: 'The Rise and Fall of Risk: A Board Game History', category: null, format: 'deep-dive' },
  { template: 'How Pandemic Predicted Our Real World', category: null, format: 'deep-dive' },
  { template: 'The Design Genius Behind Ticket to Ride', category: null, format: 'deep-dive' },
  { template: 'What Makes Terraforming Mars So Addictive', category: 'Strategy', format: 'deep-dive' },
  { template: 'The Evolution of Deck Building from Dominion to Today', category: null, format: 'deep-dive' },
  { template: 'Spirit Island Deep Dive: Mechanics, Strategy, and Lore', category: 'Cooperative', format: 'deep-dive' },
  { template: 'How Scythe Became a Modern Board Game Classic', category: 'Strategy', format: 'deep-dive' },
  { template: 'The Legacy of Carcassonne: 25 Years of Tile Laying', category: null, format: 'deep-dive' },
  { template: 'Why Brass Birmingham Is the Best Economic Game Ever Made', category: 'Economic', format: 'deep-dive' },
  { template: 'Root: The Most Asymmetric Board Game Explained', category: null, format: 'deep-dive' },
  { template: 'The Genius of 7 Wonders and Card Drafting', category: null, format: 'deep-dive' },
  { template: 'Azul: How a Simple Tile Game Won the World', category: 'Abstract', format: 'deep-dive' },
  { template: 'The Complete Guide to the Arkham Horror Universe', category: null, format: 'deep-dive' },
  { template: 'How Agricola Defined the Modern Euro Game', category: 'Economic', format: 'deep-dive' },
  { template: 'Cosmic Encounter: 50 Years of Alien Powers', category: null, format: 'deep-dive' },
  { template: 'What Makes Twilight Imperium Worth 8 Hours', category: 'Strategy', format: 'deep-dive' },
  { template: 'The Story Behind Betrayal at House on the Hill', category: null, format: 'deep-dive' },
  { template: 'Splendor: Why the Simplest Engine Builder Works So Well', category: null, format: 'deep-dive' },
  { template: 'The History of Dungeons and Dragons Board Games', category: null, format: 'deep-dive' },
  { template: 'How Concordia Hides Deep Strategy Behind Simple Rules', category: 'Strategy', format: 'deep-dive' },
  { template: 'Patchwork: The Perfect Two Player Game Dissected', category: null, format: 'deep-dive' },
  { template: 'Why Power Grid Still Holds Up After 20 Years', category: 'Economic', format: 'deep-dive' },

  // -- Seasonal / Timely (40) --
  { template: 'Best Board Games to Give This Holiday Season', category: null, format: 'buying-guide' },
  { template: 'Summer Board Games Perfect for the Beach', category: null, format: 'list' },
  { template: 'Spooky Board Games for Halloween Night', category: null, format: 'list' },
  { template: 'New Years Eve Party Game Picks', category: 'Party', format: 'list' },
  { template: 'Valentine Day Board Games for Couples', category: null, format: 'list' },
  { template: 'Board Games for Rainy Days Indoors', category: null, format: 'list' },
  { template: 'Best Board Games for Spring Break', category: null, format: 'list' },
  { template: 'Back to School Board Games for Students', category: null, format: 'list' },
  { template: 'Thanksgiving Board Games the Whole Family Will Love', category: null, format: 'list' },
  { template: 'Board Games to Play During a Snow Day', category: null, format: 'list' },
  { template: 'Best Board Games for Fourth of July Gatherings', category: null, format: 'list' },
  { template: 'Father Day Gift Guide for Board Game Dads', category: null, format: 'buying-guide' },
  { template: 'Mother Day Board Game Gift Ideas', category: null, format: 'buying-guide' },
  { template: 'Board Games for Graduation Gifts', category: null, format: 'buying-guide' },
  { template: 'Best Board Games for a Cabin Weekend', category: null, format: 'list' },
  { template: 'Board Games Perfect for Road Trip Stops', category: null, format: 'list' },
  { template: 'Games to Play at Your Holiday Party', category: 'Party', format: 'list' },
  { template: 'Board Game Stocking Stuffers Under $15', category: null, format: 'buying-guide' },
  { template: 'Best Board Games Released This Spring', category: null, format: 'list' },
  { template: 'Most Anticipated Board Games Coming This Year', category: null, format: 'list' },
  { template: 'Best Board Games for a Lazy Sunday', category: null, format: 'list' },
  { template: 'Games to Play on a Camping Trip', category: null, format: 'list' },
  { template: 'Board Games for a Cozy Winter Night', category: null, format: 'list' },
  { template: 'Board Games for Your Super Bowl Party', category: 'Party', format: 'list' },
  { template: 'Best Board Games to Play Outdoors', category: null, format: 'list' },
  { template: 'Board Games for a Friendsgiving Gathering', category: null, format: 'list' },
  { template: 'Summer Camp Board Games Kids Actually Want to Play', category: null, format: 'list' },
  { template: 'Board Games for Your Birthday Party', category: 'Party', format: 'list' },
  { template: 'Best Board Games to Play at the Cottage', category: null, format: 'list' },
  { template: 'Games Perfect for a Weekend Getaway', category: null, format: 'list' },
  { template: 'Board Games for a Housewarming Gift', category: null, format: 'buying-guide' },
  { template: 'Best Board Games for a Staycation', category: null, format: 'list' },
  { template: 'Board Games for a Bachelor or Bachelorette Party', category: 'Party', format: 'list' },
  { template: 'Games for When the Power Goes Out', category: null, format: 'list' },
  { template: 'Board Games to Play at the Airport', category: null, format: 'list' },
  { template: 'Best Board Games for a Picnic', category: null, format: 'list' },
  { template: 'Board Game Wedding Gift Ideas for Gamer Couples', category: null, format: 'buying-guide' },
  { template: 'Best Board Games for Teacher Appreciation Gifts', category: null, format: 'buying-guide' },
  { template: 'Board Games to Play on a Cruise', category: null, format: 'list' },
  { template: 'Games Perfect for a Sleepover', category: null, format: 'list' },

  // -- Buying Guides (25) --
  { template: 'Best Board Games Under $15 in 2026', category: null, format: 'buying-guide' },
  { template: 'Best Board Games Under $25 in 2026', category: null, format: 'buying-guide' },
  { template: 'Best Board Games Between $25 and $50', category: null, format: 'buying-guide' },
  { template: 'Splurge Worthy Board Games Over $75', category: null, format: 'buying-guide' },
  { template: 'Board Game Gift Guide for Teenagers', category: null, format: 'buying-guide' },
  { template: 'Board Game Gift Guide for Kids Under 10', category: null, format: 'buying-guide' },
  { template: 'Board Game Gift Guide for Parents', category: null, format: 'buying-guide' },
  { template: 'Board Game Gift Guide for Your Partner', category: null, format: 'buying-guide' },
  { template: 'Best First Board Game for a New Gamer', category: null, format: 'buying-guide' },
  { template: 'Board Games Worth Buying Deluxe Editions', category: null, format: 'buying-guide' },
  { template: 'Best Budget Strategy Games for Tight Wallets', category: 'Strategy', format: 'buying-guide' },
  { template: 'Where to Buy Board Games Online for the Best Deals', category: null, format: 'buying-guide' },
  { template: 'Best Board Games You Can Buy at Target', category: null, format: 'buying-guide' },
  { template: 'Board Games Available at Your Local Bookstore', category: null, format: 'buying-guide' },
  { template: 'Best Board Games on Amazon Right Now', category: null, format: 'buying-guide' },
  { template: 'Complete Board Game Starter Kit for New Collectors', category: null, format: 'buying-guide' },
  { template: 'Best Board Games to Buy at a Game Store', category: null, format: 'buying-guide' },
  { template: 'Board Game Accessories That Are Actually Worth It', category: null, format: 'buying-guide' },
  { template: 'Best Board Game Tables and Organizers', category: null, format: 'buying-guide' },
  { template: 'Board Games with the Best Bang for Your Buck', category: null, format: 'buying-guide' },
  { template: 'Used Board Games: What to Buy and What to Avoid', category: null, format: 'buying-guide' },
  { template: 'Best Board Game Subscription Boxes', category: null, format: 'buying-guide' },
  { template: 'Board Games That Are Worth the Premium Price', category: null, format: 'buying-guide' },
  { template: 'Best Cooperative Board Games to Buy First', category: 'Cooperative', format: 'buying-guide' },
  { template: 'Cheap Party Games That Feel Premium', category: 'Party', format: 'buying-guide' },

  // -- Beginner Guides (30) --
  { template: 'Complete Beginner Guide to Worker Placement Games', category: 'Worker Placement', format: 'guide' },
  { template: 'How Deck Building Works in Board Games', category: null, format: 'guide' },
  { template: 'Your First Euro Game: Where to Start', category: null, format: 'guide' },
  { template: 'How to Read a Board Game Rulebook Without Losing Your Mind', category: null, format: 'guide' },
  { template: 'Board Game Lingo Explained: A Glossary for New Players', category: null, format: 'guide' },
  { template: 'How Area Control Works in Board Games', category: 'Strategy', format: 'guide' },
  { template: 'Beginner Guide to Engine Building Games', category: null, format: 'guide' },
  { template: 'How to Pick Your First Strategy Board Game', category: 'Strategy', format: 'guide' },
  { template: 'What Is a Legacy Game and Should You Play One', category: null, format: 'guide' },
  { template: 'Understanding Board Game Weight and Complexity Ratings', category: null, format: 'guide' },
  { template: 'How Tile Placement Games Work', category: null, format: 'guide' },
  { template: 'Beginner Guide to Auction and Bidding Games', category: null, format: 'guide' },
  { template: 'How Set Collection Works in Board Games', category: null, format: 'guide' },
  { template: 'Beginner Guide to Route Building Games', category: null, format: 'guide' },
  { template: 'What Is a Roll and Write Game', category: null, format: 'guide' },
  { template: 'How Hand Management Works in Board Games', category: null, format: 'guide' },
  { template: 'Beginner Guide to Hidden Role Games', category: null, format: 'guide' },
  { template: 'What Are Push Your Luck Games', category: null, format: 'guide' },
  { template: 'How Simultaneous Action Selection Works', category: null, format: 'guide' },
  { template: 'Beginner Guide to Cooperative Board Games', category: 'Cooperative', format: 'guide' },
  { template: 'How Variable Player Powers Make Games Interesting', category: null, format: 'guide' },
  { template: 'What Is Asymmetric Gameplay in Board Games', category: null, format: 'guide' },
  { template: 'Beginner Guide to Economic Board Games', category: 'Economic', format: 'guide' },
  { template: 'How Campaign and Scenario Games Work', category: null, format: 'guide' },
  { template: 'What Makes a Good Gateway Game', category: null, format: 'guide' },
  { template: 'Beginner Guide to Board Game Expansions', category: null, format: 'guide' },
  { template: 'How to Teach Yourself Board Games from Rulebooks', category: null, format: 'guide' },
  { template: 'What Is Action Point Allowance in Board Games', category: null, format: 'guide' },
  { template: 'Beginner Guide to Wargames and War Board Games', category: 'Wargame', format: 'guide' },
  { template: 'How Modular Boards Make Every Game Different', category: null, format: 'guide' },

  // -- Collection Management (20) --
  { template: 'When to Sell Board Games from Your Collection', category: null, format: 'guide' },
  { template: 'How to Store 100 Plus Board Games', category: null, format: 'guide' },
  { template: 'Building the Perfect 10 Game Collection', category: null, format: 'guide' },
  { template: 'How to Organize Your Board Game Shelf', category: null, format: 'guide' },
  { template: 'The One In One Out Rule for Board Game Collectors', category: null, format: 'guide' },
  { template: 'How to Track Your Board Game Collection', category: null, format: 'guide' },
  { template: 'Board Games That Replace Multiple Other Games', category: null, format: 'list' },
  { template: 'How to Build a Diverse Game Collection', category: null, format: 'guide' },
  { template: 'When to Keep and When to Sell Board Game Expansions', category: null, format: 'guide' },
  { template: 'Board Game Storage Solutions for Small Apartments', category: null, format: 'guide' },
  { template: 'How to Rate and Review Your Board Game Collection', category: null, format: 'guide' },
  { template: 'Building a Board Game Collection on a Budget', category: null, format: 'guide' },
  { template: 'The 20 Game Collection That Covers Every Mood', category: null, format: 'list' },
  { template: 'How to Catalog Your Board Games with BGG', category: null, format: 'guide' },
  { template: 'Best Board Games to Keep in Your Car', category: null, format: 'list' },
  { template: 'How to Display Board Games as Home Decor', category: null, format: 'guide' },
  { template: 'Which Board Game Editions Are Actually Worth Upgrading', category: null, format: 'guide' },
  { template: 'How to Sell Board Games for the Best Price', category: null, format: 'guide' },
  { template: 'Building a Travel Board Game Kit', category: null, format: 'guide' },
  { template: 'How to Protect and Maintain Your Board Games', category: null, format: 'guide' },

  // -- Game Night Hosting (20) --
  { template: 'How to Teach Board Games Without Boring Everyone', category: null, format: 'guide' },
  { template: 'Planning the Perfect Board Game Night', category: null, format: 'guide' },
  { template: 'Snacks That Pair Perfectly with Board Game Night', category: null, format: 'guide' },
  { template: 'How to Handle Sore Losers at Game Night', category: null, format: 'guide' },
  { template: 'The Ideal Game Night Schedule for 4 Hours', category: null, format: 'guide' },
  { template: 'How to Introduce Non Gamers to Board Games', category: null, format: 'guide' },
  { template: 'Setting Up a Board Game Cafe at Home', category: null, format: 'guide' },
  { template: 'How to Organize a Board Game League', category: null, format: 'guide' },
  { template: 'Best Music Playlists for Board Game Night', category: null, format: 'guide' },
  { template: 'How to Pick the Right Game for Your Group', category: null, format: 'guide' },
  { template: 'Board Game Night Etiquette Everyone Should Know', category: null, format: 'guide' },
  { template: 'How to Run a Board Game Night for Beginners', category: null, format: 'guide' },
  { template: 'Creating a Board Game Rotation for Regular Groups', category: null, format: 'guide' },
  { template: 'How to Make Board Game Night a Monthly Tradition', category: null, format: 'guide' },
  { template: 'Best Board Games for an Office Game Night', category: null, format: 'list' },
  { template: 'How to Host a Board Game Night in a Small Space', category: null, format: 'guide' },
  { template: 'Board Game Night Tips for Couples Who Game Together', category: null, format: 'guide' },
  { template: 'How to Keep Game Night Fresh When Your Group Plays Weekly', category: null, format: 'guide' },
  { template: 'Best Drinks for Board Game Night', category: null, format: 'guide' },
  { template: 'How to End Game Night on a High Note', category: null, format: 'guide' },

  // -- Crossover / Lifestyle (20) --
  { template: 'Board Games for Book Club Night', category: null, format: 'list' },
  { template: 'Board Games to Play After Dinner', category: null, format: 'list' },
  { template: 'Board Games for Wine Night with Friends', category: null, format: 'list' },
  { template: 'Board Games for When You Are Bored of Streaming', category: null, format: 'list' },
  { template: 'Board Games for Long Car Rides', category: null, format: 'list' },
  { template: 'Board Games Teachers Can Use in the Classroom', category: null, format: 'list' },
  { template: 'Board Games for Team Building at Work', category: null, format: 'list' },
  { template: 'Board Games for Waiting Rooms and Downtime', category: null, format: 'list' },
  { template: 'Board Games for Recovering from Surgery or Illness', category: null, format: 'list' },
  { template: 'Board Games to Play with Grandparents', category: null, format: 'list' },
  { template: 'Board Games for Study Breaks in College', category: null, format: 'list' },
  { template: 'Board Games for Couples Who Hate Board Games', category: null, format: 'list' },
  { template: 'Board Games for People Who Love Puzzles', category: null, format: 'list' },
  { template: 'Board Games for History Buffs', category: null, format: 'list' },
  { template: 'Board Games for Math and Logic Lovers', category: null, format: 'list' },
  { template: 'Board Games for Creative and Artistic People', category: null, format: 'list' },
  { template: 'Board Games for Introverts Who Still Want to Socialize', category: null, format: 'list' },
  { template: 'Board Games for Dog and Cat Lovers', category: null, format: 'list' },
  { template: 'Board Games for Astronomy and Space Fans', category: 'Science Fiction', format: 'list' },
  { template: 'Board Games for Music Fans', category: null, format: 'list' },

  // -- Hidden Gems / Underrated (25) --
  { template: 'Hidden Gem Strategy Games Nobody Talks About', category: 'Strategy', format: 'list' },
  { template: 'Underrated Cooperative Games You Are Missing', category: 'Cooperative', format: 'list' },
  { template: '10 Board Games That Deserve Way More Attention', category: null, format: 'list' },
  { template: 'Overlooked Two Player Games That Beat the Popular Ones', category: null, format: 'list' },
  { template: 'Hidden Gem Card Games Worth Discovering', category: 'Card Game', format: 'list' },
  { template: 'Underrated Party Games That Outshine the Classics', category: 'Party', format: 'list' },
  { template: 'Board Games Under 1000 Ratings on BGG That Are Amazing', category: null, format: 'list' },
  { template: 'Small Publisher Board Games You Should Know About', category: null, format: 'list' },
  { template: 'Underrated Abstract Games for Puzzle Lovers', category: 'Abstract', format: 'list' },
  { template: 'Hidden Gem Family Games Everyone Overlooks', category: null, format: 'list' },
  { template: 'Board Games from Outside the US That Deserve Hype', category: null, format: 'list' },
  { template: 'Underrated Engine Building Games', category: null, format: 'list' },
  { template: 'Hidden Gems in the Roll and Write Genre', category: null, format: 'list' },
  { template: 'Underrated Games from Famous Designers', category: null, format: 'list' },
  { template: 'Board Games That Bombed on Kickstarter but Are Actually Great', category: null, format: 'list' },
  { template: 'Hidden Gem Economic Games for Number Crunchers', category: 'Economic', format: 'list' },
  { template: 'Overlooked Dexterity Games for All Ages', category: null, format: 'list' },
  { template: 'Underrated Games That Play Great at 3 Players', category: null, format: 'list' },
  { template: 'Hidden Gem Dice Games Beyond Yahtzee', category: 'Dice', format: 'list' },
  { template: 'Board Games from the 90s That Still Hold Up', category: null, format: 'list' },
  { template: 'Underrated Solo Board Games Worth Trying', category: null, format: 'list' },
  { template: 'Hidden Gems Under 60 Minutes', category: null, format: 'list' },
  { template: 'Board Games with Terrible Box Art but Amazing Gameplay', category: null, format: 'list' },
  { template: 'Underrated Worker Placement Games', category: 'Worker Placement', format: 'list' },
  { template: 'Games That Got Lost in a Crowded Release Year', category: null, format: 'list' },

  // -- Head-to-Head Comparisons (25) --
  { template: 'Catan vs Ticket to Ride: Which Is Better for Beginners', category: null, format: 'comparison' },
  { template: 'Gloomhaven vs Descent: The Dungeon Crawler Showdown', category: null, format: 'comparison' },
  { template: '7 Wonders vs Sushi Go: Card Drafting Face Off', category: null, format: 'comparison' },
  { template: 'Pandemic vs Spirit Island: Cooperative Game Battle', category: 'Cooperative', format: 'comparison' },
  { template: 'Wingspan vs Everdell: Nature Theme Throwdown', category: null, format: 'comparison' },
  { template: 'Terraforming Mars vs Ark Nova: Engine Building Titans', category: 'Strategy', format: 'comparison' },
  { template: 'Codenames vs Wavelength: Best Party Game Debate', category: 'Party', format: 'comparison' },
  { template: 'Azul vs Sagrada: Abstract Tile Game Showdown', category: 'Abstract', format: 'comparison' },
  { template: 'Dominion vs Star Realms: Deck Building Duel', category: null, format: 'comparison' },
  { template: 'Scythe vs Eclipse: Sci Fi Strategy Battle', category: 'Strategy', format: 'comparison' },
  { template: 'Carcassonne vs Kingdomino: Tile Placement for Families', category: null, format: 'comparison' },
  { template: 'Root vs Vast: Asymmetric Game Comparison', category: null, format: 'comparison' },
  { template: 'Patchwork vs Jaipur: Two Player Game Duel', category: null, format: 'comparison' },
  { template: 'Agricola vs Caverna: Uwe Rosenberg Farm Fight', category: 'Economic', format: 'comparison' },
  { template: 'Splendor vs Century Spice Road: Engine Building Basics', category: null, format: 'comparison' },
  { template: 'Dixit vs Mysterium: Creative Clue Game Battle', category: null, format: 'comparison' },
  { template: 'Brass Birmingham vs Great Western Trail: Heavy Euro Clash', category: 'Economic', format: 'comparison' },
  { template: 'Viticulture vs Vinhos: Wine Theme Board Game Comparison', category: null, format: 'comparison' },
  { template: 'Clank vs The Quest for El Dorado: Deck Building Races', category: null, format: 'comparison' },
  { template: 'Nemesis vs Dead of Winter: Survival Horror Board Games', category: null, format: 'comparison' },
  { template: 'Ticket to Ride vs Carcassonne: Best Gateway Game', category: null, format: 'comparison' },
  { template: 'Betrayal at House on the Hill vs Mansions of Madness', category: null, format: 'comparison' },
  { template: 'King of Tokyo vs King of New York: Monster Battle', category: null, format: 'comparison' },
  { template: 'Mage Knight vs Gloomhaven: Ultimate Solo Game Debate', category: null, format: 'comparison' },
  { template: 'Uno vs Exploding Kittens: Casual Card Game Face Off', category: 'Card Game', format: 'comparison' },

  // -- Genre Explainers (20) --
  { template: 'What Are Euro Games and Why People Love Them', category: null, format: 'guide' },
  { template: 'Ameritrash Games Explained: Theme Over Mechanics', category: null, format: 'guide' },
  { template: 'What Is a 4X Board Game', category: '4X', format: 'guide' },
  { template: 'Social Deduction Games Explained: Lying as a Mechanic', category: null, format: 'guide' },
  { template: 'What Are Dexterity Board Games', category: null, format: 'guide' },
  { template: 'Abstract Strategy Games Explained', category: 'Abstract', format: 'guide' },
  { template: 'What Is a Sandbox Board Game', category: null, format: 'guide' },
  { template: 'Dungeon Crawlers Explained: Tabletop Adventures', category: null, format: 'guide' },
  { template: 'What Is a Tableau Building Game', category: null, format: 'guide' },
  { template: 'Trick Taking Games Explained for Modern Gamers', category: null, format: 'guide' },
  { template: 'What Are Negotiation Board Games', category: null, format: 'guide' },
  { template: 'Pick Up and Deliver Games Explained', category: null, format: 'guide' },
  { template: 'What Is a Rondel Mechanic in Board Games', category: null, format: 'guide' },
  { template: 'Programmed Movement Games Explained', category: null, format: 'guide' },
  { template: 'What Is COIN and Why Wargamers Love It', category: 'Wargame', format: 'guide' },
  { template: 'Bag Building Games Explained: Upgrade Your Luck', category: null, format: 'guide' },
  { template: 'What Are Print and Play Board Games', category: null, format: 'guide' },
  { template: 'Cooperative Games vs Semi Cooperative: Key Differences', category: null, format: 'guide' },
  { template: 'What Is a Eurogame vs an Ameritrash Game Really', category: null, format: 'guide' },
  { template: 'Real Time Board Games Explained: No Turns Needed', category: null, format: 'guide' },

  // -- Narrative / Storytelling (20) --
  { template: 'Board Games That Tell Better Stories Than Movies', category: null, format: 'opinion' },
  { template: 'The 5 Most Memorable Board Game Moments of All Time', category: null, format: 'opinion' },
  { template: 'Games Where the Story Emerges from the Gameplay', category: null, format: 'deep-dive' },
  { template: 'Board Games with Twist Endings You Will Never Forget', category: null, format: 'list' },
  { template: 'How Board Games Create Better Stories Than Authors', category: null, format: 'opinion' },
  { template: 'The Most Emotional Board Game Experiences', category: null, format: 'opinion' },
  { template: 'Board Games with the Best Narrative Campaigns', category: null, format: 'list' },
  { template: 'Why Emergent Storytelling Makes Board Games Special', category: null, format: 'deep-dive' },
  { template: 'Board Games That Made You Feel Something Unexpected', category: null, format: 'opinion' },
  { template: 'The Funniest Things That Have Ever Happened in Board Games', category: null, format: 'opinion' },
  { template: 'Board Games Where Your Choices Actually Matter', category: null, format: 'list' },
  { template: 'How Board Games Handle Morality and Ethical Choices', category: null, format: 'deep-dive' },
  { template: 'Board Games with the Most Immersive Themes', category: null, format: 'list' },
  { template: 'Why Board Game Stories Beat Video Game Stories', category: null, format: 'opinion' },
  { template: 'The Best Branching Narrative Board Games', category: null, format: 'list' },
  { template: 'Board Games That Turn Strangers Into Rivals', category: null, format: 'opinion' },
  { template: 'Games Where the Table Talk Is the Best Part', category: null, format: 'list' },
  { template: 'Board Games with Incredible World Building', category: null, format: 'list' },
  { template: 'How Traitor Mechanics Create the Best Board Game Stories', category: null, format: 'deep-dive' },
  { template: 'Board Games That Play Like Choose Your Own Adventure Books', category: null, format: 'list' },

  // -- Strategy Tips (30) --
  { template: 'How to Win at Ticket to Ride: Strategy Guide', category: null, format: 'guide' },
  { template: 'Common Catan Mistakes and How to Avoid Them', category: null, format: 'guide' },
  { template: 'Advanced Wingspan Strategy for Experienced Players', category: null, format: 'guide' },
  { template: 'Terraforming Mars Strategy Tips for Every Corporation', category: 'Strategy', format: 'guide' },
  { template: 'How to Get Better at Azul', category: 'Abstract', format: 'guide' },
  { template: 'Carcassonne Strategy Guide: Beyond the Basics', category: null, format: 'guide' },
  { template: 'How to Win at 7 Wonders: Drafting Strategy', category: null, format: 'guide' },
  { template: 'Splendor Strategy Tips: When to Reserve and When to Buy', category: null, format: 'guide' },
  { template: 'Pandemic Strategy Guide: Beating the Diseases', category: 'Cooperative', format: 'guide' },
  { template: 'How to Improve Your Bluffing in Board Games', category: null, format: 'guide' },
  { template: 'Dominion Strategy Guide for Intermediate Players', category: null, format: 'guide' },
  { template: 'Root Faction Strategy Guide for Every Animal', category: null, format: 'guide' },
  { template: 'How to Think Ahead in Worker Placement Games', category: 'Worker Placement', format: 'guide' },
  { template: 'Scythe Strategy Tips: Choosing Your Faction', category: 'Strategy', format: 'guide' },
  { template: 'How to Win at Codenames: Clue Giving Tips', category: 'Party', format: 'guide' },
  { template: 'Spirit Island Strategy Guide for Solo Players', category: 'Cooperative', format: 'guide' },
  { template: 'Agricola Strategy Tips for Feeding Your Family', category: 'Economic', format: 'guide' },
  { template: 'How to Get Better at Deck Building Games', category: null, format: 'guide' },
  { template: 'Everdell Strategy Tips: Maximizing Your Seasons', category: null, format: 'guide' },
  { template: 'How to Win at King of Tokyo: Dice Strategy', category: null, format: 'guide' },
  { template: 'Great Western Trail Strategy Tips', category: 'Strategy', format: 'guide' },
  { template: 'How to Improve at Negotiation Board Games', category: null, format: 'guide' },
  { template: 'Race for the Galaxy Strategy for New Players', category: null, format: 'guide' },
  { template: 'How to Draft Better in Board Games', category: null, format: 'guide' },
  { template: 'Brass Birmingham Strategy Guide: Iron or Cotton', category: 'Economic', format: 'guide' },
  { template: 'How to Play the Long Game in Engine Builders', category: null, format: 'guide' },
  { template: 'Clank Strategy Tips: Risk vs Reward', category: null, format: 'guide' },
  { template: 'How to Read Your Opponents in Board Games', category: null, format: 'guide' },
  { template: 'Ark Nova Strategy Guide: Building the Best Zoo', category: null, format: 'guide' },
  { template: 'How to Recover from a Bad Start in Board Games', category: null, format: 'guide' },

  // -- Meta / Industry (20) --
  { template: 'Why Board Games Are More Popular Than Ever in 2026', category: null, format: 'opinion' },
  { template: 'The Rise of Crowdfunded Board Games', category: null, format: 'deep-dive' },
  { template: 'How Kickstarter Changed Board Gaming Forever', category: null, format: 'deep-dive' },
  { template: 'The State of Board Game Cafes Around the World', category: null, format: 'deep-dive' },
  { template: 'How BoardGameGeek Became the Center of the Hobby', category: null, format: 'deep-dive' },
  { template: 'Why Board Game Prices Keep Going Up', category: null, format: 'opinion' },
  { template: 'The Most Influential Board Game Designers Working Today', category: null, format: 'list' },
  { template: 'How Board Game Publishing Works Behind the Scenes', category: null, format: 'deep-dive' },
  { template: 'The Problem with Board Game Awards', category: null, format: 'opinion' },
  { template: 'Why Board Games Are the Best Screen Free Activity', category: null, format: 'opinion' },
  { template: 'How AI Is Changing Board Game Design', category: null, format: 'deep-dive' },
  { template: 'The Environmental Impact of Board Game Production', category: null, format: 'deep-dive' },
  { template: 'Why Indie Board Game Designers Deserve More Attention', category: null, format: 'opinion' },
  { template: 'How Board Game Conventions Work and Why You Should Go', category: null, format: 'guide' },
  { template: 'The Business of Board Games: Who Makes Money', category: null, format: 'deep-dive' },
  { template: 'Why Board Game Groups Are the Best Social Hobby', category: null, format: 'opinion' },
  { template: 'How Tabletop Simulator Changed Online Board Gaming', category: null, format: 'deep-dive' },
  { template: 'The Future of Board Games: Trends to Watch', category: null, format: 'opinion' },
  { template: 'How Board Games Build Skills You Use Every Day', category: null, format: 'opinion' },
  { template: 'Why the Board Game Community Is One of the Best Online', category: null, format: 'opinion' },
];

/**
 * Pick today's topic template using day-of-year modular rotation.
 *
 * Supports a `slot` parameter for multiple posts per day. With 2 slots,
 * the formula is `(dayOfYear * 2 + slot) % totalTopics`, so each slot
 * on the same day picks a different topic.
 *
 * @param date - Optional date to pick the topic for (defaults to now)
 * @param slot - Slot number for multi-post-per-day (0 or 1, default 0)
 * @returns The selected template, resolved title hint, and topic index
 */
export function pickTopic(date?: Date, slot = 0): {
  template: TopicTemplate;
  titleHint: string;
  topicIndex: number;
} {
  const now = date ?? new Date();
  const dayOfYear = Math.floor(
    (now.getTime() - new Date(now.getFullYear(), 0, 0).getTime()) / 86400000
  );
  const topicIndex = (dayOfYear * 2 + slot) % TOPIC_TEMPLATES.length;
  const template = TOPIC_TEMPLATES[topicIndex];
  const titleHint = template.template.replace('{category}', template.category ?? 'Board');

  return { template, titleHint, topicIndex };
}
