-- Add enriched_metadata column for LLM-generated game metadata enrichment.
-- Stores mood tags, vibe keywords, target audience, similar games,
-- and refined mechanic descriptions generated by GPT-4o-mini.
-- See scripts/enrich-game-metadata.ts for the batch generation script.

ALTER TABLE games ADD COLUMN IF NOT EXISTS enriched_metadata jsonb;

-- Index for querying games by enriched mood tags
CREATE INDEX IF NOT EXISTS idx_games_enriched_metadata
  ON games USING GIN (enriched_metadata);

COMMENT ON COLUMN games.enriched_metadata IS 'LLM-enriched metadata: moods, vibeKeywords, targetAudience, similarGames, refinedMechanics';
